/*
 * Copyright (C) 2011-2018 Swift Navigation Inc.
 * Contact: https://support.swiftnav.com
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

// This file was auto-generated by generate.py. Do not modify by hand!

#ifndef CHECK_SUITES_H
#define CHECK_SUITES_H

Suite* edc_suite(void);
Suite* sbp_suite(void);
Suite* bitfield_macros_suite(void);
Suite* auto_check_sbp_acquisition_1_suite(void);
Suite* auto_check_sbp_acquisition_2_suite(void);
Suite* auto_check_sbp_acquisition_3_suite(void);
Suite* auto_check_sbp_bootload_4_suite(void);
Suite* auto_check_sbp_ext_events_5_suite(void);
Suite* auto_check_sbp_imu_6_suite(void);
Suite* auto_check_sbp_imu_7_suite(void);
Suite* auto_check_sbp_logging_8_suite(void);
Suite* auto_check_sbp_logging_9_suite(void);
Suite* auto_check_sbp_logging_10_suite(void);
Suite* auto_check_sbp_navigation_11_suite(void);
Suite* auto_check_sbp_navigation_12_suite(void);
Suite* auto_check_sbp_navigation_13_suite(void);
Suite* auto_check_sbp_navigation_14_suite(void);
Suite* auto_check_sbp_navigation_15_suite(void);
Suite* auto_check_sbp_navigation_16_suite(void);
Suite* auto_check_sbp_navigation_17_suite(void);
Suite* auto_check_sbp_navigation_18_suite(void);
Suite* auto_check_sbp_navigation_19_suite(void);
Suite* auto_check_sbp_navigation_20_suite(void);
Suite* auto_check_sbp_navigation_21_suite(void);
Suite* auto_check_sbp_navigation_22_suite(void);
Suite* auto_check_sbp_navigation_23_suite(void);
Suite* auto_check_sbp_navigation_24_suite(void);
Suite* auto_check_sbp_navigation_25_suite(void);
Suite* auto_check_sbp_navigation_26_suite(void);
Suite* auto_check_sbp_navigation_27_suite(void);
Suite* auto_check_sbp_navigation_28_suite(void);
Suite* auto_check_sbp_navigation_29_suite(void);
Suite* auto_check_sbp_navigation_30_suite(void);
Suite* auto_check_sbp_navigation_31_suite(void);
Suite* auto_check_sbp_navigation_32_suite(void);
Suite* auto_check_sbp_navigation_33_suite(void);
Suite* auto_check_sbp_navigation_34_suite(void);
Suite* auto_check_sbp_navigation_35_suite(void);
Suite* auto_check_sbp_navigation_36_suite(void);
Suite* auto_check_sbp_navigation_37_suite(void);
Suite* auto_check_sbp_navigation_38_suite(void);
Suite* auto_check_sbp_navigation_39_suite(void);
Suite* auto_check_sbp_navigation_40_suite(void);
Suite* auto_check_sbp_navigation_41_suite(void);
Suite* auto_check_sbp_navigation_42_suite(void);
Suite* auto_check_sbp_navigation_43_suite(void);
Suite* auto_check_sbp_navigation_44_suite(void);
Suite* auto_check_sbp_observation_45_suite(void);
Suite* auto_check_sbp_observation_46_suite(void);
Suite* auto_check_sbp_observation_47_suite(void);
Suite* auto_check_sbp_observation_48_suite(void);
Suite* auto_check_sbp_observation_49_suite(void);
Suite* auto_check_sbp_observation_50_suite(void);
Suite* auto_check_sbp_observation_51_suite(void);
Suite* auto_check_sbp_observation_52_suite(void);
Suite* auto_check_sbp_observation_53_suite(void);
Suite* auto_check_sbp_observation_54_suite(void);
Suite* auto_check_sbp_observation_55_suite(void);
Suite* auto_check_sbp_observation_56_suite(void);
Suite* auto_check_sbp_observation_57_suite(void);
Suite* auto_check_sbp_orientation_58_suite(void);
Suite* auto_check_sbp_orientation_59_suite(void);
Suite* auto_check_sbp_orientation_60_suite(void);
Suite* auto_check_sbp_piksi_61_suite(void);
Suite* auto_check_sbp_piksi_62_suite(void);
Suite* auto_check_sbp_piksi_63_suite(void);
Suite* auto_check_sbp_piksi_64_suite(void);
Suite* auto_check_sbp_sbas_65_suite(void);
Suite* auto_check_sbp_settings_66_suite(void);
Suite* auto_check_sbp_settings_67_suite(void);
Suite* auto_check_sbp_system_68_suite(void);
Suite* auto_check_sbp_system_69_suite(void);
Suite* auto_check_sbp_system_70_suite(void);
Suite* auto_check_sbp_system_71_suite(void);
Suite* auto_check_sbp_system_72_suite(void);
Suite* auto_check_sbp_system_73_suite(void);
Suite* auto_check_sbp_tracking_74_suite(void);
Suite* auto_check_sbp_tracking_75_suite(void);
Suite* auto_check_sbp_tracking_76_suite(void);
Suite* auto_check_sbp_vehicle_77_suite(void);

#endif /* CHECK_SUITES_H */