/*
 * Copyright (C) 2011-2018 Swift Navigation Inc.
 * Contact: Swift Navigation <dev@swiftnav.com>
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

// This file was auto-generated by generate.py. Do not modify by hand!

#ifndef CHECK_SUITES_H
#define CHECK_SUITES_H

Suite* edc_suite(void);
Suite* sbp_suite(void);
Suite* auto_check_sbp_acquisition_1_suite(void);
Suite* auto_check_sbp_acquisition_2_suite(void);
Suite* auto_check_sbp_navigation_3_suite(void);
Suite* auto_check_sbp_navigation_4_suite(void);
Suite* auto_check_sbp_navigation_5_suite(void);
Suite* auto_check_sbp_navigation_6_suite(void);
Suite* auto_check_sbp_navigation_7_suite(void);
Suite* auto_check_sbp_navigation_8_suite(void);
Suite* auto_check_sbp_navigation_9_suite(void);
Suite* auto_check_sbp_navigation_10_suite(void);
Suite* auto_check_sbp_navigation_11_suite(void);
Suite* auto_check_sbp_navigation_12_suite(void);
Suite* auto_check_sbp_navigation_13_suite(void);
Suite* auto_check_sbp_navigation_14_suite(void);
Suite* auto_check_sbp_navigation_15_suite(void);
Suite* auto_check_sbp_navigation_16_suite(void);
Suite* auto_check_sbp_navigation_17_suite(void);
Suite* auto_check_sbp_navigation_18_suite(void);
Suite* auto_check_sbp_navigation_19_suite(void);
Suite* auto_check_sbp_navigation_20_suite(void);
Suite* auto_check_sbp_navigation_21_suite(void);
Suite* auto_check_sbp_navigation_22_suite(void);
Suite* auto_check_sbp_navigation_23_suite(void);
Suite* auto_check_sbp_navigation_24_suite(void);
Suite* auto_check_sbp_observation_25_suite(void);
Suite* auto_check_sbp_observation_26_suite(void);
Suite* auto_check_sbp_orientation_27_suite(void);
Suite* auto_check_sbp_orientation_28_suite(void);
Suite* auto_check_sbp_orientation_29_suite(void);
Suite* auto_check_sbp_piksi_30_suite(void);
Suite* auto_check_sbp_piksi_31_suite(void);
Suite* auto_check_sbp_piksi_32_suite(void);
Suite* auto_check_sbp_settings_33_suite(void);
Suite* auto_check_sbp_settings_34_suite(void);
Suite* auto_check_sbp_system_35_suite(void);
Suite* auto_check_sbp_system_36_suite(void);
Suite* auto_check_sbp_system_37_suite(void);
Suite* auto_check_sbp_acquisition_38_suite(void);
Suite* auto_check_sbp_bootload_39_suite(void);
Suite* auto_check_sbp_ext_events_40_suite(void);
Suite* auto_check_sbp_logging_41_suite(void);
Suite* auto_check_sbp_logging_42_suite(void);
Suite* auto_check_sbp_navigation_43_suite(void);
Suite* auto_check_sbp_observation_44_suite(void);
Suite* auto_check_sbp_piksi_45_suite(void);
Suite* auto_check_sbp_system_46_suite(void);
Suite* auto_check_sbp_tracking_47_suite(void);
Suite* auto_check_sbp_tracking_48_suite(void);
Suite* auto_check_sbp_tracking_49_suite(void);
Suite* auto_check_sbp_vehicle_50_suite(void);

#endif /* CHECK_SUITES_H */