/*
 * Copyright (C) 2011-2015 Swift Navigation Inc.
 * Contact: Fergus Noble <fergus@swift-nav.com>
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

// This file was auto-generated by generate.py. Do not modify by hand!

#ifndef CHECK_SUITES_H
#define CHECK_SUITES_H

Suite* edc_suite(void);
Suite* sbp_suite(void);
Suite* auto_check_sbp_acquisition_1_suite(void);
Suite* auto_check_sbp_navigation_2_suite(void);
Suite* auto_check_sbp_navigation_3_suite(void);
Suite* auto_check_sbp_navigation_4_suite(void);
Suite* auto_check_sbp_navigation_5_suite(void);
Suite* auto_check_sbp_navigation_6_suite(void);
Suite* auto_check_sbp_navigation_7_suite(void);
Suite* auto_check_sbp_navigation_8_suite(void);
Suite* auto_check_sbp_navigation_9_suite(void);
Suite* auto_check_sbp_observation_10_suite(void);
Suite* auto_check_sbp_observation_11_suite(void);
Suite* auto_check_sbp_piksi_12_suite(void);
Suite* auto_check_sbp_piksi_13_suite(void);
Suite* auto_check_sbp_piksi_14_suite(void);
Suite* auto_check_sbp_settings_15_suite(void);
Suite* auto_check_sbp_settings_16_suite(void);
Suite* auto_check_sbp_system_17_suite(void);
Suite* auto_check_sbp_acquisition_18_suite(void);
Suite* auto_check_sbp_bootload_19_suite(void);
Suite* auto_check_sbp_ext_events_20_suite(void);
Suite* auto_check_sbp_logging_21_suite(void);
Suite* auto_check_sbp_navigation_22_suite(void);
Suite* auto_check_sbp_observation_23_suite(void);
Suite* auto_check_sbp_piksi_24_suite(void);
Suite* auto_check_sbp_system_25_suite(void);
Suite* auto_check_sbp_tracking_26_suite(void);
Suite* auto_check_sbp_tracking_27_suite(void);

#endif /* CHECK_SUITES_H */