/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#ifndef PB_SWIFTNAV_SBP_ACQUISITION_ACQUISITION_PB_H_INCLUDED
#define PB_SWIFTNAV_SBP_ACQUISITION_ACQUISITION_PB_H_INCLUDED
#include <pb.h>

#include "gnss.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _swiftnav_sbp_acquisition_MsgAcqSvProfile {
    pb_callback_t acq_sv_profile;
/* @@protoc_insertion_point(struct:swiftnav_sbp_acquisition_MsgAcqSvProfile) */
} swiftnav_sbp_acquisition_MsgAcqSvProfile;

typedef struct _swiftnav_sbp_acquisition_AcqSvProfile {
    uint32_t job_type;
    uint32_t status;
    uint32_t cn0;
    uint32_t int_time;
    swiftnav_sbp_gnss_GnssSignal sid;
    uint32_t bin_width;
    uint32_t timestamp;
    uint32_t time_spent;
    int32_t cf_min;
    int32_t cf_max;
    int32_t cf;
    uint32_t cp;
/* @@protoc_insertion_point(struct:swiftnav_sbp_acquisition_AcqSvProfile) */
} swiftnav_sbp_acquisition_AcqSvProfile;

typedef struct _swiftnav_sbp_acquisition_MsgAcqResult {
    float cn0;
    float cp;
    float cf;
    swiftnav_sbp_gnss_GnssSignal sid;
/* @@protoc_insertion_point(struct:swiftnav_sbp_acquisition_MsgAcqResult) */
} swiftnav_sbp_acquisition_MsgAcqResult;

/* Default values for struct fields */

/* Initializer values for message structs */
#define swiftnav_sbp_acquisition_MsgAcqResult_init_default {0, 0, 0, swiftnav_sbp_gnss_GnssSignal_init_default}
#define swiftnav_sbp_acquisition_AcqSvProfile_init_default {0, 0, 0, 0, swiftnav_sbp_gnss_GnssSignal_init_default, 0, 0, 0, 0, 0, 0, 0}
#define swiftnav_sbp_acquisition_MsgAcqSvProfile_init_default {{{NULL}, NULL}}
#define swiftnav_sbp_acquisition_MsgAcqResult_init_zero {0, 0, 0, swiftnav_sbp_gnss_GnssSignal_init_zero}
#define swiftnav_sbp_acquisition_AcqSvProfile_init_zero {0, 0, 0, 0, swiftnav_sbp_gnss_GnssSignal_init_zero, 0, 0, 0, 0, 0, 0, 0}
#define swiftnav_sbp_acquisition_MsgAcqSvProfile_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define swiftnav_sbp_acquisition_MsgAcqSvProfile_acq_sv_profile_tag 1
#define swiftnav_sbp_acquisition_AcqSvProfile_job_type_tag 1
#define swiftnav_sbp_acquisition_AcqSvProfile_status_tag 2
#define swiftnav_sbp_acquisition_AcqSvProfile_cn0_tag 3
#define swiftnav_sbp_acquisition_AcqSvProfile_int_time_tag 4
#define swiftnav_sbp_acquisition_AcqSvProfile_sid_tag 5
#define swiftnav_sbp_acquisition_AcqSvProfile_bin_width_tag 6
#define swiftnav_sbp_acquisition_AcqSvProfile_timestamp_tag 7
#define swiftnav_sbp_acquisition_AcqSvProfile_time_spent_tag 8
#define swiftnav_sbp_acquisition_AcqSvProfile_cf_min_tag 9
#define swiftnav_sbp_acquisition_AcqSvProfile_cf_max_tag 10
#define swiftnav_sbp_acquisition_AcqSvProfile_cf_tag 11
#define swiftnav_sbp_acquisition_AcqSvProfile_cp_tag 12
#define swiftnav_sbp_acquisition_MsgAcqResult_cn0_tag 1
#define swiftnav_sbp_acquisition_MsgAcqResult_cp_tag 2
#define swiftnav_sbp_acquisition_MsgAcqResult_cf_tag 3
#define swiftnav_sbp_acquisition_MsgAcqResult_sid_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t swiftnav_sbp_acquisition_MsgAcqResult_fields[5];
extern const pb_field_t swiftnav_sbp_acquisition_AcqSvProfile_fields[13];
extern const pb_field_t swiftnav_sbp_acquisition_MsgAcqSvProfile_fields[2];

/* Maximum encoded size of messages (where known) */
#define swiftnav_sbp_acquisition_MsgAcqResult_size 29
#define swiftnav_sbp_acquisition_AcqSvProfile_size 80
/* swiftnav_sbp_acquisition_MsgAcqSvProfile_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ACQUISITION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
