/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#ifndef PB_SWIFTNAV_SBP_EXT_EVENTS_EXT_EVENTS_PB_H_INCLUDED
#define PB_SWIFTNAV_SBP_EXT_EVENTS_EXT_EVENTS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _swiftnav_sbp_ext_events_MsgExtEvent {
    uint32_t wn;
    uint32_t tow;
    int32_t ns_residual;
    uint32_t flags;
    uint32_t pin;
/* @@protoc_insertion_point(struct:swiftnav_sbp_ext_events_MsgExtEvent) */
} swiftnav_sbp_ext_events_MsgExtEvent;

/* Default values for struct fields */

/* Initializer values for message structs */
#define swiftnav_sbp_ext_events_MsgExtEvent_init_default {0, 0, 0, 0, 0}
#define swiftnav_sbp_ext_events_MsgExtEvent_init_zero {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define swiftnav_sbp_ext_events_MsgExtEvent_wn_tag 1
#define swiftnav_sbp_ext_events_MsgExtEvent_tow_tag 2
#define swiftnav_sbp_ext_events_MsgExtEvent_ns_residual_tag 3
#define swiftnav_sbp_ext_events_MsgExtEvent_flags_tag 4
#define swiftnav_sbp_ext_events_MsgExtEvent_pin_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t swiftnav_sbp_ext_events_MsgExtEvent_fields[6];

/* Maximum encoded size of messages (where known) */
#define swiftnav_sbp_ext_events_MsgExtEvent_size 30

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define EXT_EVENTS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
