/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#ifndef PB_SWIFTNAV_SBP_FILE_IO_FILE_IO_PB_H_INCLUDED
#define PB_SWIFTNAV_SBP_FILE_IO_FILE_IO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _swiftnav_sbp_file_io_MsgFileioRemove {
    pb_callback_t filename;
/* @@protoc_insertion_point(struct:swiftnav_sbp_file_io_MsgFileioRemove) */
} swiftnav_sbp_file_io_MsgFileioRemove;

typedef struct _swiftnav_sbp_file_io_MsgFileioReadDirReq {
    uint32_t sequence;
    uint32_t offset;
    pb_callback_t dirname;
/* @@protoc_insertion_point(struct:swiftnav_sbp_file_io_MsgFileioReadDirReq) */
} swiftnav_sbp_file_io_MsgFileioReadDirReq;

typedef struct _swiftnav_sbp_file_io_MsgFileioReadDirResp {
    uint32_t sequence;
    pb_callback_t contents;
/* @@protoc_insertion_point(struct:swiftnav_sbp_file_io_MsgFileioReadDirResp) */
} swiftnav_sbp_file_io_MsgFileioReadDirResp;

typedef struct _swiftnav_sbp_file_io_MsgFileioReadReq {
    uint32_t sequence;
    uint32_t offset;
    uint32_t chunk_size;
    pb_callback_t filename;
/* @@protoc_insertion_point(struct:swiftnav_sbp_file_io_MsgFileioReadReq) */
} swiftnav_sbp_file_io_MsgFileioReadReq;

typedef struct _swiftnav_sbp_file_io_MsgFileioReadResp {
    uint32_t sequence;
    pb_callback_t contents;
/* @@protoc_insertion_point(struct:swiftnav_sbp_file_io_MsgFileioReadResp) */
} swiftnav_sbp_file_io_MsgFileioReadResp;

typedef struct _swiftnav_sbp_file_io_MsgFileioWriteReq {
    uint32_t sequence;
    uint32_t offset;
    pb_callback_t filename;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:swiftnav_sbp_file_io_MsgFileioWriteReq) */
} swiftnav_sbp_file_io_MsgFileioWriteReq;

typedef struct _swiftnav_sbp_file_io_MsgFileioWriteResp {
    uint32_t sequence;
/* @@protoc_insertion_point(struct:swiftnav_sbp_file_io_MsgFileioWriteResp) */
} swiftnav_sbp_file_io_MsgFileioWriteResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define swiftnav_sbp_file_io_MsgFileioReadReq_init_default {0, 0, 0, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioReadResp_init_default {0, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioReadDirReq_init_default {0, 0, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioReadDirResp_init_default {0, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioRemove_init_default {{{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioWriteReq_init_default {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioWriteResp_init_default {0}
#define swiftnav_sbp_file_io_MsgFileioReadReq_init_zero {0, 0, 0, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioReadResp_init_zero {0, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioReadDirReq_init_zero {0, 0, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioReadDirResp_init_zero {0, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioRemove_init_zero {{{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioWriteReq_init_zero {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define swiftnav_sbp_file_io_MsgFileioWriteResp_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define swiftnav_sbp_file_io_MsgFileioRemove_filename_tag 1
#define swiftnav_sbp_file_io_MsgFileioReadDirReq_sequence_tag 1
#define swiftnav_sbp_file_io_MsgFileioReadDirReq_offset_tag 2
#define swiftnav_sbp_file_io_MsgFileioReadDirReq_dirname_tag 3
#define swiftnav_sbp_file_io_MsgFileioReadDirResp_sequence_tag 1
#define swiftnav_sbp_file_io_MsgFileioReadDirResp_contents_tag 2
#define swiftnav_sbp_file_io_MsgFileioReadReq_sequence_tag 1
#define swiftnav_sbp_file_io_MsgFileioReadReq_offset_tag 2
#define swiftnav_sbp_file_io_MsgFileioReadReq_chunk_size_tag 3
#define swiftnav_sbp_file_io_MsgFileioReadReq_filename_tag 4
#define swiftnav_sbp_file_io_MsgFileioReadResp_sequence_tag 1
#define swiftnav_sbp_file_io_MsgFileioReadResp_contents_tag 2
#define swiftnav_sbp_file_io_MsgFileioWriteReq_sequence_tag 1
#define swiftnav_sbp_file_io_MsgFileioWriteReq_offset_tag 2
#define swiftnav_sbp_file_io_MsgFileioWriteReq_filename_tag 3
#define swiftnav_sbp_file_io_MsgFileioWriteReq_data_tag 4
#define swiftnav_sbp_file_io_MsgFileioWriteResp_sequence_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t swiftnav_sbp_file_io_MsgFileioReadReq_fields[5];
extern const pb_field_t swiftnav_sbp_file_io_MsgFileioReadResp_fields[3];
extern const pb_field_t swiftnav_sbp_file_io_MsgFileioReadDirReq_fields[4];
extern const pb_field_t swiftnav_sbp_file_io_MsgFileioReadDirResp_fields[3];
extern const pb_field_t swiftnav_sbp_file_io_MsgFileioRemove_fields[2];
extern const pb_field_t swiftnav_sbp_file_io_MsgFileioWriteReq_fields[5];
extern const pb_field_t swiftnav_sbp_file_io_MsgFileioWriteResp_fields[2];

/* Maximum encoded size of messages (where known) */
/* swiftnav_sbp_file_io_MsgFileioReadReq_size depends on runtime parameters */
/* swiftnav_sbp_file_io_MsgFileioReadResp_size depends on runtime parameters */
/* swiftnav_sbp_file_io_MsgFileioReadDirReq_size depends on runtime parameters */
/* swiftnav_sbp_file_io_MsgFileioReadDirResp_size depends on runtime parameters */
/* swiftnav_sbp_file_io_MsgFileioRemove_size depends on runtime parameters */
/* swiftnav_sbp_file_io_MsgFileioWriteReq_size depends on runtime parameters */
#define swiftnav_sbp_file_io_MsgFileioWriteResp_size 6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FILE_IO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
