/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#include "imu.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t swiftnav_sbp_imu_MsgImuRaw_fields[9] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, swiftnav_sbp_imu_MsgImuRaw, tow, tow, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_imu_MsgImuRaw, tow_f, tow, 0),
    PB_FIELD(  3, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_imu_MsgImuRaw, acc_x, tow_f, 0),
    PB_FIELD(  4, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_imu_MsgImuRaw, acc_y, acc_x, 0),
    PB_FIELD(  5, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_imu_MsgImuRaw, acc_z, acc_y, 0),
    PB_FIELD(  6, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_imu_MsgImuRaw, gyr_x, acc_z, 0),
    PB_FIELD(  7, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_imu_MsgImuRaw, gyr_y, gyr_x, 0),
    PB_FIELD(  8, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_imu_MsgImuRaw, gyr_z, gyr_y, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_imu_MsgImuAux_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, swiftnav_sbp_imu_MsgImuAux, imu_type, imu_type, 0),
    PB_FIELD(  2, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_imu_MsgImuAux, temp, imu_type, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_imu_MsgImuAux, imu_conf, temp, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
