/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#ifndef PB_SWIFTNAV_SBP_LOGGING_LOGGING_PB_H_INCLUDED
#define PB_SWIFTNAV_SBP_LOGGING_LOGGING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _swiftnav_sbp_logging_MsgTweet {
    pb_callback_t tweet;
/* @@protoc_insertion_point(struct:swiftnav_sbp_logging_MsgTweet) */
} swiftnav_sbp_logging_MsgTweet;

typedef struct _swiftnav_sbp_logging_MsgFwd {
    uint32_t source;
    uint32_t protocol;
    pb_callback_t fwd_payload;
/* @@protoc_insertion_point(struct:swiftnav_sbp_logging_MsgFwd) */
} swiftnav_sbp_logging_MsgFwd;

typedef struct _swiftnav_sbp_logging_MsgLog {
    uint32_t level;
    pb_callback_t text;
/* @@protoc_insertion_point(struct:swiftnav_sbp_logging_MsgLog) */
} swiftnav_sbp_logging_MsgLog;

/* Default values for struct fields */

/* Initializer values for message structs */
#define swiftnav_sbp_logging_MsgLog_init_default {0, {{NULL}, NULL}}
#define swiftnav_sbp_logging_MsgFwd_init_default {0, 0, {{NULL}, NULL}}
#define swiftnav_sbp_logging_MsgTweet_init_default {{{NULL}, NULL}}
#define swiftnav_sbp_logging_MsgLog_init_zero    {0, {{NULL}, NULL}}
#define swiftnav_sbp_logging_MsgFwd_init_zero    {0, 0, {{NULL}, NULL}}
#define swiftnav_sbp_logging_MsgTweet_init_zero  {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define swiftnav_sbp_logging_MsgTweet_tweet_tag  1
#define swiftnav_sbp_logging_MsgFwd_source_tag   1
#define swiftnav_sbp_logging_MsgFwd_protocol_tag 2
#define swiftnav_sbp_logging_MsgFwd_fwd_payload_tag 3
#define swiftnav_sbp_logging_MsgLog_level_tag    1
#define swiftnav_sbp_logging_MsgLog_text_tag     2

/* Struct field encoding specification for nanopb */
extern const pb_field_t swiftnav_sbp_logging_MsgLog_fields[3];
extern const pb_field_t swiftnav_sbp_logging_MsgFwd_fields[4];
extern const pb_field_t swiftnav_sbp_logging_MsgTweet_fields[2];

/* Maximum encoded size of messages (where known) */
/* swiftnav_sbp_logging_MsgLog_size depends on runtime parameters */
/* swiftnav_sbp_logging_MsgFwd_size depends on runtime parameters */
/* swiftnav_sbp_logging_MsgTweet_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LOGGING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
