/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#ifndef PB_SWIFTNAV_SBP_MAG_MAG_PB_H_INCLUDED
#define PB_SWIFTNAV_SBP_MAG_MAG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _swiftnav_sbp_mag_MsgMagRaw {
    uint32_t tow;
    uint32_t tow_f;
    int32_t mag_x;
    int32_t mag_y;
    int32_t mag_z;
/* @@protoc_insertion_point(struct:swiftnav_sbp_mag_MsgMagRaw) */
} swiftnav_sbp_mag_MsgMagRaw;

/* Default values for struct fields */

/* Initializer values for message structs */
#define swiftnav_sbp_mag_MsgMagRaw_init_default  {0, 0, 0, 0, 0}
#define swiftnav_sbp_mag_MsgMagRaw_init_zero     {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define swiftnav_sbp_mag_MsgMagRaw_tow_tag       1
#define swiftnav_sbp_mag_MsgMagRaw_tow_f_tag     2
#define swiftnav_sbp_mag_MsgMagRaw_mag_x_tag     3
#define swiftnav_sbp_mag_MsgMagRaw_mag_y_tag     4
#define swiftnav_sbp_mag_MsgMagRaw_mag_z_tag     5

/* Struct field encoding specification for nanopb */
extern const pb_field_t swiftnav_sbp_mag_MsgMagRaw_fields[6];

/* Maximum encoded size of messages (where known) */
#define swiftnav_sbp_mag_MsgMagRaw_size          30

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MAG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
