/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#include "orientation.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t swiftnav_sbp_orientation_MsgBaselineHeading_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, swiftnav_sbp_orientation_MsgBaselineHeading, tow, tow, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgBaselineHeading, heading, tow, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgBaselineHeading, n_sats, heading, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgBaselineHeading, flags, n_sats, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_orientation_MsgOrientQuat_fields[11] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, swiftnav_sbp_orientation_MsgOrientQuat, tow, tow, 0),
    PB_FIELD(  2, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientQuat, w, tow, 0),
    PB_FIELD(  3, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientQuat, x, w, 0),
    PB_FIELD(  4, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientQuat, y, x, 0),
    PB_FIELD(  5, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientQuat, z, y, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientQuat, acc_w, z, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientQuat, acc_x, acc_w, 0),
    PB_FIELD(  8, FLOAT   , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientQuat, acc_y, acc_x, 0),
    PB_FIELD(  9, FLOAT   , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientQuat, acc_z, acc_y, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientQuat, flags, acc_z, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_orientation_MsgOrientEuler_fields[9] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, swiftnav_sbp_orientation_MsgOrientEuler, tow, tow, 0),
    PB_FIELD(  2, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientEuler, roll, tow, 0),
    PB_FIELD(  3, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientEuler, pitch, roll, 0),
    PB_FIELD(  4, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientEuler, yaw, pitch, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientEuler, var_roll, yaw, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientEuler, var_pitch, var_roll, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientEuler, var_yaw, var_pitch, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgOrientEuler, flags, var_yaw, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_orientation_MsgAngularRate_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, swiftnav_sbp_orientation_MsgAngularRate, tow, tow, 0),
    PB_FIELD(  2, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgAngularRate, x, tow, 0),
    PB_FIELD(  3, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgAngularRate, y, x, 0),
    PB_FIELD(  4, SINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgAngularRate, z, y, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, swiftnav_sbp_orientation_MsgAngularRate, flags, z, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
