/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#include "settings.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t swiftnav_sbp_settings_MsgSettingsSave_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_settings_MsgSettingsWrite_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, swiftnav_sbp_settings_MsgSettingsWrite, setting, setting, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_settings_MsgSettingsWriteResp_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, swiftnav_sbp_settings_MsgSettingsWriteResp, status, status, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, swiftnav_sbp_settings_MsgSettingsWriteResp, setting, status, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_settings_MsgSettingsReadReq_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, swiftnav_sbp_settings_MsgSettingsReadReq, setting, setting, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_settings_MsgSettingsReadResp_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, swiftnav_sbp_settings_MsgSettingsReadResp, setting, setting, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_settings_MsgSettingsReadByIndexReq_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, swiftnav_sbp_settings_MsgSettingsReadByIndexReq, index, index, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_settings_MsgSettingsReadByIndexResp_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, swiftnav_sbp_settings_MsgSettingsReadByIndexResp, index, index, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, swiftnav_sbp_settings_MsgSettingsReadByIndexResp, setting, index, 0),
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_settings_MsgSettingsReadByIndexDone_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t swiftnav_sbp_settings_MsgSettingsRegister_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, swiftnav_sbp_settings_MsgSettingsRegister, setting, setting, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
