/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#ifndef PB_SWIFTNAV_SBP_SSR_SSR_PB_H_INCLUDED
#define PB_SWIFTNAV_SBP_SSR_SSR_PB_H_INCLUDED
#include <pb.h>

#include "gnss.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _swiftnav_sbp_ssr_CodeBiasesContent {
    uint32_t code;
    int32_t value;
/* @@protoc_insertion_point(struct:swiftnav_sbp_ssr_CodeBiasesContent) */
} swiftnav_sbp_ssr_CodeBiasesContent;

typedef struct _swiftnav_sbp_ssr_MsgSsrCodeBiases {
    swiftnav_sbp_gnss_GpsTimeSec time;
    swiftnav_sbp_gnss_GnssSignal sid;
    uint32_t update_interval;
    uint32_t iod_ssr;
    pb_callback_t biases;
/* @@protoc_insertion_point(struct:swiftnav_sbp_ssr_MsgSsrCodeBiases) */
} swiftnav_sbp_ssr_MsgSsrCodeBiases;

typedef struct _swiftnav_sbp_ssr_MsgSsrOrbitClock {
    swiftnav_sbp_gnss_GpsTimeSec time;
    swiftnav_sbp_gnss_GnssSignal sid;
    uint32_t update_interval;
    uint32_t iod_ssr;
    uint32_t iod;
    int32_t radial;
    int32_t along;
    int32_t cross;
    int32_t dot_radial;
    int32_t dot_along;
    int32_t dot_cross;
    int32_t c0;
    int32_t c1;
    int32_t c2;
/* @@protoc_insertion_point(struct:swiftnav_sbp_ssr_MsgSsrOrbitClock) */
} swiftnav_sbp_ssr_MsgSsrOrbitClock;

typedef struct _swiftnav_sbp_ssr_MsgSsrPhaseBiases {
    swiftnav_sbp_gnss_GpsTimeSec time;
    swiftnav_sbp_gnss_GnssSignal sid;
    uint32_t update_interval;
    uint32_t iod_ssr;
    uint32_t dispersive_bias;
    uint32_t mw_consistency;
    uint32_t yaw;
    int32_t yaw_rate;
    pb_callback_t biases;
/* @@protoc_insertion_point(struct:swiftnav_sbp_ssr_MsgSsrPhaseBiases) */
} swiftnav_sbp_ssr_MsgSsrPhaseBiases;

typedef struct _swiftnav_sbp_ssr_PhaseBiasesContent {
    uint32_t code;
    uint32_t integer_indicator;
    uint32_t widelane_integer_indicator;
    uint32_t discontinuity_counter;
    int32_t bias;
/* @@protoc_insertion_point(struct:swiftnav_sbp_ssr_PhaseBiasesContent) */
} swiftnav_sbp_ssr_PhaseBiasesContent;

/* Default values for struct fields */

/* Initializer values for message structs */
#define swiftnav_sbp_ssr_CodeBiasesContent_init_default {0, 0}
#define swiftnav_sbp_ssr_PhaseBiasesContent_init_default {0, 0, 0, 0, 0}
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_init_default {swiftnav_sbp_gnss_GpsTimeSec_init_default, swiftnav_sbp_gnss_GnssSignal_init_default, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define swiftnav_sbp_ssr_MsgSsrCodeBiases_init_default {swiftnav_sbp_gnss_GpsTimeSec_init_default, swiftnav_sbp_gnss_GnssSignal_init_default, 0, 0, {{NULL}, NULL}}
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_init_default {swiftnav_sbp_gnss_GpsTimeSec_init_default, swiftnav_sbp_gnss_GnssSignal_init_default, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}}
#define swiftnav_sbp_ssr_CodeBiasesContent_init_zero {0, 0}
#define swiftnav_sbp_ssr_PhaseBiasesContent_init_zero {0, 0, 0, 0, 0}
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_init_zero {swiftnav_sbp_gnss_GpsTimeSec_init_zero, swiftnav_sbp_gnss_GnssSignal_init_zero, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define swiftnav_sbp_ssr_MsgSsrCodeBiases_init_zero {swiftnav_sbp_gnss_GpsTimeSec_init_zero, swiftnav_sbp_gnss_GnssSignal_init_zero, 0, 0, {{NULL}, NULL}}
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_init_zero {swiftnav_sbp_gnss_GpsTimeSec_init_zero, swiftnav_sbp_gnss_GnssSignal_init_zero, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define swiftnav_sbp_ssr_CodeBiasesContent_code_tag 1
#define swiftnav_sbp_ssr_CodeBiasesContent_value_tag 2
#define swiftnav_sbp_ssr_MsgSsrCodeBiases_time_tag 1
#define swiftnav_sbp_ssr_MsgSsrCodeBiases_sid_tag 2
#define swiftnav_sbp_ssr_MsgSsrCodeBiases_update_interval_tag 3
#define swiftnav_sbp_ssr_MsgSsrCodeBiases_iod_ssr_tag 4
#define swiftnav_sbp_ssr_MsgSsrCodeBiases_biases_tag 5
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_time_tag 1
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_sid_tag 2
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_update_interval_tag 3
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_iod_ssr_tag 4
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_iod_tag 5
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_radial_tag 6
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_along_tag 7
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_cross_tag 8
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_dot_radial_tag 9
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_dot_along_tag 10
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_dot_cross_tag 11
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_c0_tag 12
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_c1_tag 13
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_c2_tag 14
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_time_tag 1
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_sid_tag 2
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_update_interval_tag 3
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_iod_ssr_tag 4
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_dispersive_bias_tag 5
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_mw_consistency_tag 6
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_yaw_tag 7
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_yaw_rate_tag 8
#define swiftnav_sbp_ssr_MsgSsrPhaseBiases_biases_tag 9
#define swiftnav_sbp_ssr_PhaseBiasesContent_code_tag 1
#define swiftnav_sbp_ssr_PhaseBiasesContent_integer_indicator_tag 2
#define swiftnav_sbp_ssr_PhaseBiasesContent_widelane_integer_indicator_tag 3
#define swiftnav_sbp_ssr_PhaseBiasesContent_discontinuity_counter_tag 4
#define swiftnav_sbp_ssr_PhaseBiasesContent_bias_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t swiftnav_sbp_ssr_CodeBiasesContent_fields[3];
extern const pb_field_t swiftnav_sbp_ssr_PhaseBiasesContent_fields[6];
extern const pb_field_t swiftnav_sbp_ssr_MsgSsrOrbitClock_fields[15];
extern const pb_field_t swiftnav_sbp_ssr_MsgSsrCodeBiases_fields[6];
extern const pb_field_t swiftnav_sbp_ssr_MsgSsrPhaseBiases_fields[10];

/* Maximum encoded size of messages (where known) */
#define swiftnav_sbp_ssr_CodeBiasesContent_size  12
#define swiftnav_sbp_ssr_PhaseBiasesContent_size 30
#define swiftnav_sbp_ssr_MsgSsrOrbitClock_size   100
/* swiftnav_sbp_ssr_MsgSsrCodeBiases_size depends on runtime parameters */
/* swiftnav_sbp_ssr_MsgSsrPhaseBiases_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SSR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
