/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#include "user.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t swiftnav_sbp_user_MsgUserData_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, CALLBACK, FIRST, swiftnav_sbp_user_MsgUserData, contents, contents, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
