/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Tue Mar 13 13:32:36 2018. */

#ifndef PB_SWIFTNAV_SBP_VEHICLE_VEHICLE_PB_H_INCLUDED
#define PB_SWIFTNAV_SBP_VEHICLE_VEHICLE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _swiftnav_sbp_vehicle_MsgOdometry {
    uint32_t tow;
    int32_t velocity;
    uint32_t flags;
/* @@protoc_insertion_point(struct:swiftnav_sbp_vehicle_MsgOdometry) */
} swiftnav_sbp_vehicle_MsgOdometry;

/* Default values for struct fields */

/* Initializer values for message structs */
#define swiftnav_sbp_vehicle_MsgOdometry_init_default {0, 0, 0}
#define swiftnav_sbp_vehicle_MsgOdometry_init_zero {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define swiftnav_sbp_vehicle_MsgOdometry_tow_tag 1
#define swiftnav_sbp_vehicle_MsgOdometry_velocity_tag 2
#define swiftnav_sbp_vehicle_MsgOdometry_flags_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t swiftnav_sbp_vehicle_MsgOdometry_fields[4];

/* Maximum encoded size of messages (where known) */
#define swiftnav_sbp_vehicle_MsgOdometry_size    18

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define VEHICLE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
