# Copyright (C) 2020 Swift Navigation Inc.
# Contact: https://support.swiftnav.com
#
# This source is subject to the license found in the file 'LICENSE' which must
# be distributed together with this source. All other rights reserved.
#
# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.

# This describes an image that should be able to generate libsbp bindings.
# See the README.md for instructions on how to use it.

FROM ubuntu:bionic

ARG DEBIAN_FRONTEND=noninteractive

ENV RUSTUP_HOME=/rust
ENV CARGO_HOME=/cargo
ENV PATH=/usr/lib/ccache:/cargo/bin:/rust/bin:${PATH}

RUN \
     apt-get update \
  && apt-get install -y \
      git \
      sudo \
      software-properties-common \
      apt-utils \
      wget \
      curl \
      build-essential \
      pandoc \
      llvm \
      nodejs \
      npm \
      mocha \
      gradle \
      texlive-science \
      texlive-fonts-extra \
      haskell-stack \
      haskell-platform \
      check \
      cmake \
      ccache \
      pkg-config \
      doxygen \
      graphviz \
      texlive-latex-base \
      imagemagick \
      libudev-dev \
      uuid-dev \
  && npm install npm@latest -g \
  && add-apt-repository ppa:deadsnakes/ppa \
  && apt-get update \
  && apt-get install -y \
      python-pip \
      python3 \
      python3-pip \
      python3.5-dev python3.5-venv python3.5-distutils \
      python3.8-dev python3.8-venv python3.8-distutils \
  && pip3 install tox \
  && pip install sphinx \
  && rm -rf /var/lib/apt/lists/* \
  && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable --no-modify-path

# Add a "dockerdev" user with sudo capabilities
# 1000 is the first user ID issued on Ubuntu; might
# be different for Mac users. Might need to add more.
RUN useradd -u 1000 -ms /bin/bash -G sudo dockerdev \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers \
    && find $RUSTUP_HOME -exec chmod a+rw {} \; \
    && find $CARGO_HOME -exec chmod a+rw {} \;

WORKDIR /mnt/workspace
USER dockerdev

RUN stack install --resolver lts-10.10 sbp
