[tox]
minversion = 4.0
skipsdist = True
envlist = py

[testenv]
allowlist_externals =
  make
deps =
  -rrequirements.txt
  numpy
commands = python -m sbpg.generator {posargs}

[testenv:autoflake]
skip_install = true
deps = autoflake
commands = autoflake -i --remove-all-unused-imports -r python/sbp

[testenv:docs]
skip_install = true
allowlist_externals =
  make
deps =
  -r{toxinidir}/python/docs/requirements.txt
  {toxinidir}/python
commands = make -C python/docs spelling html
