#!/usr/bin/env python
# Copyright (C) 2015-2023 Swift Navigation Inc.
# Contact: https://support.swiftnav.com
#
# This source is subject to the license found in the file 'LICENSE' which must
# be be distributed together with this source. All other rights reserved.
#
# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.

"""
Generator for Kaitai Struct python tests.

This module consumes the YAML test spec and generates test caes for the
python bindings generated by kaitai-struct-compiler
"""

from sbpg.targets.kaitai import snake_case
from sbpg.targets.common import string_type
from sbpg.targets.templating import JENV

TEMPLATE_NAME = "sbp_test_kaitai_python.j2"

JENV.filters['snake_case'] = snake_case
JENV.filters['str_escape'] = repr

JENV.tests['string_type'] = string_type


def render_source(output_dir, package_spec, jenv=JENV):
  """
  Render and output a PY file containing test cases
  """
  path, name = package_spec.filepath
  destination_filename = "{}/test_{}.py".format(output_dir, name)
  py_template = JENV.get_template(TEMPLATE_NAME)
  with open(destination_filename, 'w') as f:
    f.write(py_template.render(s=package_spec))
