# Copyright (C) 2015 Swift Navigation Inc.
# Contact: Fergus Noble <fergus@swiftnav.com>
#
# This source is subject to the license found in the file 'LICENSE' which must
# be be distributed together with this source. All other rights reserved.
#
# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.

package: swiftnav.sbp.settings
description: |
  Messages for reading and writing the device's device settings.

  These are in the implementation-defined range (0x0000-0x00FF). Note
  that some of these messages share the same message type ID for both
  the host request and the device response. See the accompanying
  document for descriptions of settings configurations and examples:
  https://github.com/swift-nav/piksi\_firmware/blob/master/docs/settings.pdf
stable: False
public: True
include:
  - types.yaml
definitions:

 - MSG_SETTINGS:
    id: 0x00A0
    public: True
    short_desc: |
      R/W device configuration settings (host <=> device)
    desc: |
      The setting message reads and writes the device's configuration.
    fields:
      - setting:
          type: string
          desc: |
            A NULL-terminated and delimited string with contents
            [SECTION_SETTING, SETTING, VALUE] on writes or a series of
            such strings on reads.

 - MSG_SETTINGS_SAVE:
    id: 0x00A1
    public: True
    short_desc: Save settings to flash (host => device)
    desc: |
      The save settings message persists the device's current settings
      configuration to its onboard flash memory file system.

 - MSG_SETTINGS_READ_BY_INDEX:
    id: 0x00A2
    short_desc: Read setting by direct index (host <=> device)
    public: False
    desc: |
      The settings message for iterating through the settings
      values. It will read the setting at an index, returning a
      NULL-terminated and delimited string with contents
      [SECTION_SETTING, SETTING, VALUE].
    fields:
      - index:
          type: u16
          desc: |
            An index into the device settings, with values ranging from
            0 to length(settings)
