#######################################################################
###                                                                 ###
### WARNING: This file is generated, please update the template at: ###
###            generator/sbpg/targets/resources/sbp-cargo.toml      ###
###                                                                 ###
#######################################################################

[package]
name = "sbp"
version = "3.2.0"
description = "Rust native implementation of SBP (Swift Binary Protocol) for communicating with devices made by Swift Navigation"
authors = ["Swift Navigation <dev@swiftnav.com>"]
repository = "https://github.com/swift-nav/libsbp"
license = "LGPL-3.0"
categories = ["parsing"]
edition = "2018"
keywords = ["encoding", "parsing"]

[features]
sbp_serde = ["serde"]
sbp2json = ["sbp_serde", "serde_json", "base64", "float-pretty-print", "dtoa"]

[lib]
path = "src/lib.rs"

[dependencies]
byteorder = "1.2.1"
crc16 = "*"
nom = "5.1.1"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
dtoa = { version = "0.4", optional = true }
base64 = { version = "0.12", optional = true }
float-pretty-print = { version = "0.1", optional = true }

[dev-dependencies]
serialport = "2.1.0"

[badges]
travis-ci = { repository = "swift-nav/libsbp" }