#######################################################################
###                                                                 ###
### WARNING: This file is generated, please update the template at: ###
###            generator/sbpg/targets/resources/sbp-cargo.toml      ###
###                                                                 ###
#######################################################################

[package]
name = "sbp"
version = "3.4.11-alpha"
description = "Rust native implementation of SBP (Swift Binary Protocol) for communicating with devices made by Swift Navigation"
authors = ["Swift Navigation <dev@swiftnav.com>"]
repository = "https://github.com/swift-nav/libsbp"
license = "MIT"
categories = ["parsing"]
edition = "2018"
keywords = ["encoding", "parsing"]

[features]
default = []
async = ["futures", "dencode/async"]
json = ["serde", "serde_json", "base64"]
link = ["slotmap"]

[lib]
path = "src/lib.rs"

[dependencies]
bytes = "1"
crc16 = "0.4"
log = "0.4"

[dependencies.swiftnav]
version = "0.7"
optional = true

[dependencies.slotmap]
version = "1"
optional = true

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true

[dependencies.serde_json]
version = "1.0"
optional = true

[dependencies.base64]
version = "0.13"
optional = true

[dependencies.futures]
version = "0.3"
optional = true

[dependencies.dencode]
version = "0.3"
default-features = false

[dev-dependencies]
serialport = "2.1.0"