#########################################################################
###                                                                   ###
### WARNING: This file is generated, please update the template at:   ###
###            generator/sbpg/targets/resources/rust/sbp_cargo.toml   ###
###                                                                   ###
#########################################################################

[package]
name = "sbp"
version = "6.3.1-alpha"
description = "Rust native implementation of SBP (Swift Binary Protocol) for communicating with devices made by Swift Navigation"
authors = ["Swift Navigation <dev@swiftnav.com>"]
repository = "https://github.com/swift-nav/libsbp"
license = "MIT"
categories = ["parsing"]
edition = "2024"
keywords = ["encoding", "parsing"]
readme = "../../README.md"

[features]
default = []
async = ["futures", "dencode/async"]
serde = ["dep:serde", "serde-big-array"]
json = ["serde", "serde_json", "base64"]
float_roundtrip = ["serde", "serde_json/float_roundtrip"]
link = ["slotmap"]

[lib]
path = "src/lib.rs"

[dependencies]
bytes = "1.10.1"
crc16 = "0.4"
log = "0.4.28"

[dependencies.swiftnav]
version = "0.10"
optional = true

[dependencies.slotmap]
version = "1.0.7"
optional = true

[dependencies.serde]
version = "1.0.228"
features = ["derive"]
optional = true

[dependencies.serde_json]
version = "1.0.145"
optional = true

[dependencies.serde-big-array]
version = "0.5.1"
optional = true

[dependencies.base64]
version = "0.22.1"
optional = true

[dependencies.futures]
version = "0.3.31"
optional = true

[dependencies.dencode]
version = "0.3"
default-features = false

[dev-dependencies]
serialport = "2.1.0"

[package.metadata.docs.rs]
# Whether to pass `--all-features` to Cargo when building docs for docs.rs
all-features = true
