#######################################################################
###                                                                 ###
### WARNING: This file is generated, please update the template at: ###
###            generator/sbpg/targets/resources/sbp-cargo.toml      ###
###                                                                 ###
#######################################################################

[package]
name = "sbp"
version = "3.4.4"
description = "Rust native implementation of SBP (Swift Binary Protocol) for communicating with devices made by Swift Navigation"
authors = ["Swift Navigation <dev@swiftnav.com>"]
repository = "https://github.com/swift-nav/libsbp"
license = "MIT"
categories = ["parsing"]
edition = "2018"
keywords = ["encoding", "parsing"]

[features]
default = ["blocking"]
blocking = ["futures_codec/blocking"]
async = ["futures", "futures_codec/async"]
sbp_serde = ["serde"]
json = ["sbp_serde", "serde_json", "base64"]

[lib]
path = "src/lib.rs"

[dependencies]
byteorder = "1.2"
bytes = "0.6"
crc16 = "*"
enum_dispatch = "0.3"
log = "0.4"
nom = "6.0"
thiserror = "1.0"

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true

[dependencies.serde_json]
version = "1"
optional = true

[dependencies.base64]
version = "0.13"
optional = true

[dependencies.futures]
version = "0.3"
optional = true

[dependencies.futures_codec]
git = "https://github.com/swift-nav/futures-codec.git"
branch = "notoriaga/sync"
default-features = false

[dev-dependencies]
serialport = "2.1.0"

[badges]
travis-ci = { repository = "swift-nav/libsbp" }
