// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type Mag struct {
	_io *kaitai.Stream
	_root *Mag
	_parent interface{}
}
func NewMag() *Mag {
	return &Mag{
	}
}

func (this *Mag) Read(io *kaitai.Stream, parent interface{}, root *Mag) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}

/**
 * Raw data from the magnetometer.
 */
type Mag_MsgMagRaw struct {
	Tow uint32
	TowF uint8
	MagX int16
	MagY int16
	MagZ int16
	_io *kaitai.Stream
	_root *Mag
	_parent *Sbp_SbpMessage
}
func NewMag_MsgMagRaw() *Mag_MsgMagRaw {
	return &Mag_MsgMagRaw{
	}
}

func (this *Mag_MsgMagRaw) Read(io *kaitai.Stream, parent *Sbp_SbpMessage, root *Mag) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Tow = uint32(tmp1)
	tmp2, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TowF = tmp2
	tmp3, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.MagX = int16(tmp3)
	tmp4, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.MagY = int16(tmp4)
	tmp5, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.MagZ = int16(tmp5)
	return err
}

/**
 * Milliseconds since start of GPS week. If the high bit is set, the
 * time is unknown or invalid.
 */

/**
 * Milliseconds since start of GPS week, fractional part
 */

/**
 * Magnetic field in the body frame X axis
 */

/**
 * Magnetic field in the body frame Y axis
 */

/**
 * Magnetic field in the body frame Z axis
 */
