# Copyright (C) 2015 Swift Navigation Inc.
# Contact: Fergus Noble <fergus@swiftnav.com>
#
# This source is subject to the license found in the file 'LICENSE' which must
# be be distributed together with this source. All other rights reserved.
#
# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.

package: swiftnav.sbp.logging
description: |
  Logging and debugging messages from the device. These are in the
  implementation-defined range (0x0000-0x00FF).
stable: True
public: True
include:
  - types.yaml
definitions:

 - MSG_LOG:
    id: 0x0401
    short_desc: Plaintext logging messages with levels
    desc: |
      This message contains a human-readable payload string from the
      device containing errors, warnings and informational messages at
      ERROR, WARNING, DEBUG, INFO logging levels.
    fields:
      - level:
          type: u8
          desc: Logging level
          fields:
              - 3-7:
                    desc: Reserved
              - 0-2:
                    desc: Logging level
                    values:
                        - 0: EMERG
                        - 1: ALERT
                        - 2: CRIT
                        - 3: ERROR
                        - 4: WARN
                        - 5: NOTICE
                        - 6: INFO
                        - 7: DEBUG
      - text:
          type: string
          desc: Human-readable string

 - MSG_TWEET:
    id: 0x0012
    short_desc: Tweet
    desc: All the news fit to tweet.
    public: False
    fields:
      - tweet:
          type: string
          size: 140
          desc: Human-readable string

 - MSG_PRINT_DEP:
    id: 0x0010
    short_desc: Deprecated
    desc: Deprecated.
    public: False
    replaced_by:
      - MSG_LOG
    fields:
      - text:
          type: string
          desc: Human-readable string

