#ifndef LIBSBP_TRACKING_MESSAGES_H
#define LIBSBP_TRACKING_MESSAGES_H

#include <endian.h>
#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include <libsbp/common.h>
#include <libsbp/unpacked/gnss.h>
/** Detailed signal tracking channel states. DEPRECATED.
 *
 * The tracking message returns a set tracking channel parameters for a
 * single tracking channel useful for debugging issues.
 */
#define SBP_MSG_TRACKING_STATE_DETAILED_DEP_A 0x0021

#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__MASK (0xff)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__SHIFT) & SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__GPS_L1CA (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__GPS_L2CM (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__SBAS_L1CA (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__GLO_L1CA (3)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__GLO_L2CA (4)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__GPS_L1P (5)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__GPS_L2P (6)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__BDS2_B1 (12)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__BDS2_B2 (13)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__GAL_E1B (14)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__GAL_E7I (20)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SID_CODE__BDS3_B2A (47)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_NO_SYNCHRONIZATION (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_BIT_SYNCHRONIZATION (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_WORD_SYNCHRONIZATION (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SUB_FRAME_SYNCHRONIZATION_MESSAGE_SYNCHRONIZATION \
  (3)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_SHIFT (3u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_WEEK_NUMBER_IS_NOT_VALID (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_WEEK_NUMBER_IS_VALID (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_TOW_IS_NOT_AVAILABLE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_DECODED_TOW_IS_AVAILABLE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TOW_FLAGS_TOW_STATUS_PROPAGATED_TOW_IS_AVAILABLE (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_SHIFT (4u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_FLL_IS_INACTIVE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_FLL_STATUS_FLL_IS_ACTIVE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_SHIFT (3u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_PLL_IS_INACTIVE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_PLL_STATUS_PLL_IS_ACTIVE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_NO_LOCKS (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_FLLDLL_LOCK (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_PLL_OPTIMISTIC_LOCK (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_TRACK_FLAGS_TRACKING_LOOP_STATUS_PLL_PESSIMISTIC_LOCK (3)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_SHIFT (4u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_ALMANAC_IS_NOT_AVAILABLE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_ALMANAC_IS_AVAILABLE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_SHIFT (3u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_EPHEMERIS_IS_NOT_AVAILABLE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_EPHEMERIS_IS_AVAILABLE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_HEALTH_IS_UNKNOWN (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_SIGNAL_IS_UNHEALTHY (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_NAV_FLAGS_HEALTH_STATUS_SIGNAL_IS_HEALTHY (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_1_MS_INTEGRATION_TIME (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_5_MS_INTEGRATION_TIME (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_10_MS_INTEGRATION_TIME (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_PSET_FLAGS_PARAMETER_SETS_20_MS_INTEGRATION_TIME (3)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_SHIFT (5u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_CLOCK_OFFSET_AND_DRIFT_IS_NOT_VALID (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CLOCK_VALIDITY_STATUS_CLOCK_OFFSET_AND_DRIFT_IS_VALID (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_SHIFT (4u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_PSEUDORANGE_IS_NOT_VALID (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_PSEUDORANGE_IS_VALID (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_SHIFT (3u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_ACCELERATION_IS_NOT_VALID (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_ACCELERATION_IS_VALID (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_SHIFT (2u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_UNRESOLVED (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_RESOLVED (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_MASK (0x3)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_RE_ACQUISITION (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_A_MISC_FLAGS_TRACKING_CHANNEL_STATUS_RUNNING (1)
typedef struct
{

  /**
   * Receiver clock time.[ns]
   */
  u64 recv_time;
  /**
   * Time of transmission of signal from satellite. TOW only valid when
   * TOW status is decoded or propagated. WN only valid when week
   * number valid flag is set.
   */
  sbp_sbp_gps_time_t tot;
  /**
   * Pseudorange observation. Valid only when pseudorange valid flag is
   * set.[2 cm]
   */
  u32 P;
  /**
   * Pseudorange observation standard deviation. Valid only when
   * pseudorange valid flag is set.[2 cm]
   */
  u16 P_std;
  /**
   * Carrier phase observation with typical sign convention. Valid only
   * when PLL pessimistic lock is achieved.[cycles]
   */
  sbp_carrier_phase_t L;
  /**
   * Carrier-to-Noise density[dB Hz / 4]
   */
  u8 cn0;
  /**
   * Lock time. It is encoded according to DF402 from the RTCM 10403.2
   * Amendment 2 specification. Valid values range from 0 to 15.
   */
  u16 lock;
  /**
   * GNSS signal identifier.
   */
  sbp_sbp_gnss_signal_t sid;
  /**
   * Carrier Doppler frequency.[Hz / 16]
   */
  s32 doppler;
  /**
   * Carrier Doppler frequency standard deviation.[Hz / 16]
   */
  u16 doppler_std;
  /**
   * Number of seconds of continuous tracking. Specifies how much time
   * signal is in continuous track.[s]
   */
  u32 uptime;
  /**
   * TCXO clock offset. Valid only when valid clock valid flag is set.[s / (2 ^ 20)]
   */
  s16 clock_offset;
  /**
   * TCXO clock drift. Valid only when valid clock valid flag is set.[(s / s) / (2 ^ 31)]
   */
  s16 clock_drift;
  /**
   * Early-Prompt (EP) and Prompt-Late (PL) correlators spacing.[ns]
   */
  u16 corr_spacing;
  /**
   * Acceleration. Valid only when acceleration valid flag is set.[g / 8]
   */
  s8 acceleration;
  /**
   * Synchronization status flags.
   */
  u8 sync_flags;
  /**
   * TOW status flags.
   */
  u8 tow_flags;
  /**
   * Tracking loop status flags.
   */
  u8 track_flags;
  /**
   * Navigation data status flags.
   */
  u8 nav_flags;
  /**
   * Parameters sets flags.
   */
  u8 pset_flags;
  /**
   * Miscellaneous flags.
   */
  u8 misc_flags;
} sbp_msg_tracking_state_detailed_dep_a_t;
/** Deprecated
 *
 * Deprecated.
 */
#define SBP_MSG_TRACKING_STATE_DETAILED_DEP 0x0011

#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__MASK (0xff)
#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__SHIFT) & SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__GPS_L1CA (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__GPS_L2CM (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__SBAS_L1CA (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__GLO_L1CA (3)
#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__GLO_L2CA (4)
#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__GPS_L1P (5)
#define SBP_TRACKING_STATE_DETAILED_DEP_SID_CODE__GPS_L2P (6)
#define SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_NO_SYNCHRONIZATION (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_BIT_SYNCHRONIZATION (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_WORD_SYNCHRONIZATION (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_SYNC_FLAGS_SYNCHRONIZATION_STATUS_SUB_FRAME_SYNCHRONIZATION_MESSAGE_SYNCHRONIZATION \
  (3)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_SHIFT (3u)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_WEEK_NUMBER_IS_NOT_VALID (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_WEEK_NUMBER_VALIDITY_STATUS_WEEK_NUMBER_IS_VALID (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_TOW_IS_NOT_AVAILABLE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_DECODED_TOW_IS_AVAILABLE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_TOW_FLAGS_TOW_STATUS_PROPAGATED_TOW_IS_AVAILABLE (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_SHIFT (4u)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_FLL_IS_INACTIVE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_FLL_STATUS_FLL_IS_ACTIVE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_SHIFT (3u)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_PLL_IS_INACTIVE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_PLL_STATUS_PLL_IS_ACTIVE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_NO_LOCKS (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_FLLDLL_LOCK (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_PLL_OPTIMISTIC_LOCK (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_TRACK_FLAGS_TRACKING_LOOP_STATUS_PLL_PESSIMISTIC_LOCK (3)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_SHIFT (4u)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_ALMANAC_IS_NOT_AVAILABLE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_ALMANAC_AVAILABILITY_STATUS_ALMANAC_IS_AVAILABLE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_SHIFT (3u)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_EPHEMERIS_IS_NOT_AVAILABLE (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_EPHEMERIS_AVAILABILITY_STATUS_EPHEMERIS_IS_AVAILABLE (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_HEALTH_IS_UNKNOWN (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_SIGNAL_IS_UNHEALTHY (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_NAV_FLAGS_HEALTH_STATUS_SIGNAL_IS_HEALTHY (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_MASK (0x7)
#define SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_1_MS_INTEGRATION_TIME (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_5_MS_INTEGRATION_TIME (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_10_MS_INTEGRATION_TIME (2)
#define SBP_TRACKING_STATE_DETAILED_DEP_PSET_FLAGS_PARAMETER_SETS_20_MS_INTEGRATION_TIME (3)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_SHIFT (5u)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_CLOCK_OFFSET_AND_DRIFT_IS_NOT_VALID (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CLOCK_VALIDITY_STATUS_CLOCK_OFFSET_AND_DRIFT_IS_VALID (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_SHIFT (4u)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_PSEUDORANGE_IS_NOT_VALID (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_PSEUDORANGE_VALIDITY_STATUS_PSEUDORANGE_IS_VALID (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_SHIFT (3u)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_ACCELERATION_IS_NOT_VALID (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_ACCELERATION_VALIDITY_STATUS_ACCELERATION_IS_VALID (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_MASK (0x1)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_SHIFT (2u)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_UNRESOLVED (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_CARRIER_HALF_CYCLE_AMBIGUITY_STATUS_RESOLVED (1)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_MASK (0x3)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_SHIFT (0u)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_SHIFT) & \
   SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_MASK)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_MASK)) \
                 << (SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_RE_ACQUISITION (0)
#define SBP_TRACKING_STATE_DETAILED_DEP_MISC_FLAGS_TRACKING_CHANNEL_STATUS_RUNNING (1)
typedef struct
{

  /**
   * Receiver clock time.[ns]
   */
  u64 recv_time;
  /**
   * Time of transmission of signal from satellite. TOW only valid when
   * TOW status is decoded or propagated. WN only valid when week
   * number valid flag is set.
   */
  sbp_gps_time_dep_t tot;
  /**
   * Pseudorange observation. Valid only when pseudorange valid flag is
   * set.[2 cm]
   */
  u32 P;
  /**
   * Pseudorange observation standard deviation. Valid only when
   * pseudorange valid flag is set.[2 cm]
   */
  u16 P_std;
  /**
   * Carrier phase observation with typical sign convention. Valid only
   * when PLL pessimistic lock is achieved.[cycles]
   */
  sbp_carrier_phase_t L;
  /**
   * Carrier-to-Noise density[dB Hz / 4]
   */
  u8 cn0;
  /**
   * Lock time. It is encoded according to DF402 from the RTCM 10403.2
   * Amendment 2 specification. Valid values range from 0 to 15.
   */
  u16 lock;
  /**
   * GNSS signal identifier.
   */
  sbp_gnss_signal_dep_t sid;
  /**
   * Carrier Doppler frequency.[Hz / 16]
   */
  s32 doppler;
  /**
   * Carrier Doppler frequency standard deviation.[Hz / 16]
   */
  u16 doppler_std;
  /**
   * Number of seconds of continuous tracking. Specifies how much time
   * signal is in continuous track.[s]
   */
  u32 uptime;
  /**
   * TCXO clock offset. Valid only when valid clock valid flag is set.[s / (2 ^ 20)]
   */
  s16 clock_offset;
  /**
   * TCXO clock drift. Valid only when valid clock valid flag is set.[(s / s) / (2 ^ 31)]
   */
  s16 clock_drift;
  /**
   * Early-Prompt (EP) and Prompt-Late (PL) correlators spacing.[ns]
   */
  u16 corr_spacing;
  /**
   * Acceleration. Valid only when acceleration valid flag is set.[g / 8]
   */
  s8 acceleration;
  /**
   * Synchronization status flags.
   */
  u8 sync_flags;
  /**
   * TOW status flags.
   */
  u8 tow_flags;
  /**
   * Tracking loop status flags.
   */
  u8 track_flags;
  /**
   * Navigation data status flags.
   */
  u8 nav_flags;
  /**
   * Parameters sets flags.
   */
  u8 pset_flags;
  /**
   * Miscellaneous flags.
   */
  u8 misc_flags;
} sbp_msg_tracking_state_detailed_dep_t;
/** Signal tracking channel state
 *
 * Tracking channel state for a specific satellite signal and
 * measured signal power.
 */

#define SBP_TRACKINGCHANNELSTATE_SID_CODE__MASK (0xff)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__SHIFT (0u)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__GET(flags) \
  (((flags) >> SBP_TRACKINGCHANNELSTATE_SID_CODE__SHIFT) & SBP_TRACKINGCHANNELSTATE_SID_CODE__MASK)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKINGCHANNELSTATE_SID_CODE__MASK)) << (SBP_TRACKINGCHANNELSTATE_SID_CODE__SHIFT))); \
  } while (0)

#define SBP_TRACKINGCHANNELSTATE_SID_CODE__GPS_L1CA (0)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__GPS_L2CM (1)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__SBAS_L1CA (2)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__GLO_L1CA (3)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__GLO_L2CA (4)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__GPS_L1P (5)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__GPS_L2P (6)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__BDS2_B1 (12)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__BDS2_B2 (13)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__GAL_E1B (14)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__GAL_E7I (20)
#define SBP_TRACKINGCHANNELSTATE_SID_CODE__BDS3_B2A (47)
typedef struct
{

  /**
   * GNSS signal being tracked
   */
  sbp_sbp_gnss_signal_t sid;
  /**
   * Frequency channel number (GLONASS only)
   */
  u8 fcn;
  /**
   * Carrier-to-Noise density.  Zero implies invalid cn0.[dB Hz / 4]
   */
  u8 cn0;
} sbp_tracking_channel_state_t;
/** Signal tracking channel states
 *
 * The tracking message returns a variable-length array of tracking
 * channel states. It reports status and carrier-to-noise density
 * measurements for all tracked satellites.
 */
#define SBP_MSG_TRACKING_STATE 0x0041

#define SBP_TRACKING_STATE_STATES_SID_CODE__MASK (0xff)
#define SBP_TRACKING_STATE_STATES_SID_CODE__SHIFT (0u)
#define SBP_TRACKING_STATE_STATES_SID_CODE__GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_STATES_SID_CODE__SHIFT) & SBP_TRACKING_STATE_STATES_SID_CODE__MASK)
#define SBP_TRACKING_STATE_STATES_SID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= \
     (((val) & (SBP_TRACKING_STATE_STATES_SID_CODE__MASK)) << (SBP_TRACKING_STATE_STATES_SID_CODE__SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_STATES_SID_CODE__GPS_L1CA (0)
#define SBP_TRACKING_STATE_STATES_SID_CODE__GPS_L2CM (1)
#define SBP_TRACKING_STATE_STATES_SID_CODE__SBAS_L1CA (2)
#define SBP_TRACKING_STATE_STATES_SID_CODE__GLO_L1CA (3)
#define SBP_TRACKING_STATE_STATES_SID_CODE__GLO_L2CA (4)
#define SBP_TRACKING_STATE_STATES_SID_CODE__GPS_L1P (5)
#define SBP_TRACKING_STATE_STATES_SID_CODE__GPS_L2P (6)
#define SBP_TRACKING_STATE_STATES_SID_CODE__BDS2_B1 (12)
#define SBP_TRACKING_STATE_STATES_SID_CODE__BDS2_B2 (13)
#define SBP_TRACKING_STATE_STATES_SID_CODE__GAL_E1B (14)
#define SBP_TRACKING_STATE_STATES_SID_CODE__GAL_E7I (20)
#define SBP_TRACKING_STATE_STATES_SID_CODE__BDS3_B2A (47)
typedef struct
{

  /**
   * Signal tracking channel state
   */
  sbp_tracking_channel_state_t states[63];
  /**
   * Number of items in states
   */
  u8 n_states;
} sbp_msg_tracking_state_t;
/** Measurement Engine signal tracking channel state
 *
 * Measurement Engine tracking channel state for a specific satellite signal
 * and measured signal power.
 * The mesid field for Glonass can either
 * carry the FCN as 100 + FCN where FCN is in [-7, +6] or
 * the Slot ID (from 1 to 28)
 */

#define SBP_MEASUREMENTSTATE_MESID_CODE__MASK (0xff)
#define SBP_MEASUREMENTSTATE_MESID_CODE__SHIFT (0u)
#define SBP_MEASUREMENTSTATE_MESID_CODE__GET(flags) \
  (((flags) >> SBP_MEASUREMENTSTATE_MESID_CODE__SHIFT) & SBP_MEASUREMENTSTATE_MESID_CODE__MASK)
#define SBP_MEASUREMENTSTATE_MESID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_MEASUREMENTSTATE_MESID_CODE__MASK)) << (SBP_MEASUREMENTSTATE_MESID_CODE__SHIFT))); \
  } while (0)

#define SBP_MEASUREMENTSTATE_MESID_CODE__GPS_L1CA (0)
#define SBP_MEASUREMENTSTATE_MESID_CODE__GPS_L2CM (1)
#define SBP_MEASUREMENTSTATE_MESID_CODE__SBAS_L1CA (2)
#define SBP_MEASUREMENTSTATE_MESID_CODE__GLO_L1CA (3)
#define SBP_MEASUREMENTSTATE_MESID_CODE__GLO_L2CA (4)
#define SBP_MEASUREMENTSTATE_MESID_CODE__GPS_L1P (5)
#define SBP_MEASUREMENTSTATE_MESID_CODE__GPS_L2P (6)
#define SBP_MEASUREMENTSTATE_MESID_CODE__BDS2_B1 (12)
#define SBP_MEASUREMENTSTATE_MESID_CODE__BDS2_B2 (13)
#define SBP_MEASUREMENTSTATE_MESID_CODE__GAL_E1B (14)
#define SBP_MEASUREMENTSTATE_MESID_CODE__GAL_E7I (20)
#define SBP_MEASUREMENTSTATE_MESID_CODE__BDS3_B2A (47)
typedef struct
{

  /**
   * Measurement Engine GNSS signal being tracked (carries either Glonass FCN or SLOT)
   */
  sbp_sbp_gnss_signal_t mesid;
  /**
   * Carrier-to-Noise density.  Zero implies invalid cn0.[dB Hz / 4]
   */
  u8 cn0;
} sbp_measurement_state_t;
/** Measurement Engine signal tracking channel states
 *
 * The tracking message returns a variable-length array of tracking
 * channel states. It reports status and carrier-to-noise density
 * measurements for all tracked satellites.
 */
#define SBP_MSG_MEASUREMENT_STATE 0x0061

#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__MASK (0xff)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__SHIFT (0u)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__GET(flags) \
  (((flags) >> SBP_MEASUREMENT_STATE_STATES_MESID_CODE__SHIFT) & SBP_MEASUREMENT_STATE_STATES_MESID_CODE__MASK)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= \
     (((val) & (SBP_MEASUREMENT_STATE_STATES_MESID_CODE__MASK)) << (SBP_MEASUREMENT_STATE_STATES_MESID_CODE__SHIFT))); \
  } while (0)

#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__GPS_L1CA (0)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__GPS_L2CM (1)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__SBAS_L1CA (2)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__GLO_L1CA (3)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__GLO_L2CA (4)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__GPS_L1P (5)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__GPS_L2P (6)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__BDS2_B1 (12)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__BDS2_B2 (13)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__GAL_E1B (14)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__GAL_E7I (20)
#define SBP_MEASUREMENT_STATE_STATES_MESID_CODE__BDS3_B2A (47)
typedef struct
{

  /**
   * ME signal tracking channel state
   */
  sbp_measurement_state_t states[85];
  /**
   * Number of items in states
   */
  u8 n_states;
} sbp_msg_measurement_state_t;
/** Complex correlation structure
 *
 * Structure containing in-phase and quadrature correlation components.
 */

typedef struct
{

  /**
   * In-phase correlation
   */
  s16 I;
  /**
   * Quadrature correlation
   */
  s16 Q;
} sbp_tracking_channel_correlation_t;
/** Tracking channel correlations
 *
 * When enabled, a tracking channel can output the correlations at each
 * update interval.
 */
#define SBP_MSG_TRACKING_IQ 0x002D

#define SBP_TRACKING_IQ_SID_CODE__MASK (0xff)
#define SBP_TRACKING_IQ_SID_CODE__SHIFT (0u)
#define SBP_TRACKING_IQ_SID_CODE__GET(flags) \
  (((flags) >> SBP_TRACKING_IQ_SID_CODE__SHIFT) & SBP_TRACKING_IQ_SID_CODE__MASK)
#define SBP_TRACKING_IQ_SID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_IQ_SID_CODE__MASK)) << (SBP_TRACKING_IQ_SID_CODE__SHIFT))); \
  } while (0)

#define SBP_TRACKING_IQ_SID_CODE__GPS_L1CA (0)
#define SBP_TRACKING_IQ_SID_CODE__GPS_L2CM (1)
#define SBP_TRACKING_IQ_SID_CODE__SBAS_L1CA (2)
#define SBP_TRACKING_IQ_SID_CODE__GLO_L1CA (3)
#define SBP_TRACKING_IQ_SID_CODE__GLO_L2CA (4)
#define SBP_TRACKING_IQ_SID_CODE__GPS_L1P (5)
#define SBP_TRACKING_IQ_SID_CODE__GPS_L2P (6)
#define SBP_TRACKING_IQ_SID_CODE__BDS2_B1 (12)
#define SBP_TRACKING_IQ_SID_CODE__BDS2_B2 (13)
#define SBP_TRACKING_IQ_SID_CODE__GAL_E1B (14)
#define SBP_TRACKING_IQ_SID_CODE__GAL_E7I (20)
#define SBP_TRACKING_IQ_SID_CODE__BDS3_B2A (47)

typedef struct
{

  /**
   * Tracking channel of origin
   */
  u8 channel;
  /**
   * GNSS signal identifier
   */
  sbp_sbp_gnss_signal_t sid;
  /**
   * Early, Prompt and Late correlations
   */
  sbp_tracking_channel_correlation_t corrs[3];
} sbp_msg_tracking_iq_t;
/** Complex correlation structure
 *
 * Structure containing in-phase and quadrature correlation components.
 */

typedef struct
{

  /**
   * In-phase correlation
   */
  s32 I;
  /**
   * Quadrature correlation
   */
  s32 Q;
} sbp_tracking_channel_correlation_dep_t;
/** Tracking channel correlations
 *
 * When enabled, a tracking channel can output the correlations at each
 * update interval.
 */
#define SBP_MSG_TRACKING_IQ_DEP_B 0x002C

#define SBP_TRACKING_IQ_DEP_B_SID_CODE__MASK (0xff)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__SHIFT (0u)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__GET(flags) \
  (((flags) >> SBP_TRACKING_IQ_DEP_B_SID_CODE__SHIFT) & SBP_TRACKING_IQ_DEP_B_SID_CODE__MASK)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_IQ_DEP_B_SID_CODE__MASK)) << (SBP_TRACKING_IQ_DEP_B_SID_CODE__SHIFT))); \
  } while (0)

#define SBP_TRACKING_IQ_DEP_B_SID_CODE__GPS_L1CA (0)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__GPS_L2CM (1)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__SBAS_L1CA (2)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__GLO_L1CA (3)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__GLO_L2CA (4)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__GPS_L1P (5)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__GPS_L2P (6)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__BDS2_B1 (12)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__BDS2_B2 (13)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__GAL_E1B (14)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__GAL_E7I (20)
#define SBP_TRACKING_IQ_DEP_B_SID_CODE__BDS3_B2A (47)

typedef struct
{

  /**
   * Tracking channel of origin
   */
  u8 channel;
  /**
   * GNSS signal identifier
   */
  sbp_sbp_gnss_signal_t sid;
  /**
   * Early, Prompt and Late correlations
   */
  sbp_tracking_channel_correlation_dep_t corrs[3];
} sbp_msg_tracking_iq_dep_b_t;
/** Deprecated
 *
 * Deprecated.
 */
#define SBP_MSG_TRACKING_IQ_DEP_A 0x001C

#define SBP_TRACKING_IQ_DEP_A_SID_CODE__MASK (0xff)
#define SBP_TRACKING_IQ_DEP_A_SID_CODE__SHIFT (0u)
#define SBP_TRACKING_IQ_DEP_A_SID_CODE__GET(flags) \
  (((flags) >> SBP_TRACKING_IQ_DEP_A_SID_CODE__SHIFT) & SBP_TRACKING_IQ_DEP_A_SID_CODE__MASK)
#define SBP_TRACKING_IQ_DEP_A_SID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_IQ_DEP_A_SID_CODE__MASK)) << (SBP_TRACKING_IQ_DEP_A_SID_CODE__SHIFT))); \
  } while (0)

#define SBP_TRACKING_IQ_DEP_A_SID_CODE__GPS_L1CA (0)
#define SBP_TRACKING_IQ_DEP_A_SID_CODE__GPS_L2CM (1)
#define SBP_TRACKING_IQ_DEP_A_SID_CODE__SBAS_L1CA (2)
#define SBP_TRACKING_IQ_DEP_A_SID_CODE__GLO_L1CA (3)
#define SBP_TRACKING_IQ_DEP_A_SID_CODE__GLO_L2CA (4)
#define SBP_TRACKING_IQ_DEP_A_SID_CODE__GPS_L1P (5)
#define SBP_TRACKING_IQ_DEP_A_SID_CODE__GPS_L2P (6)

typedef struct
{

  /**
   * Tracking channel of origin
   */
  u8 channel;
  /**
   * GNSS signal identifier
   */
  sbp_gnss_signal_dep_t sid;
  /**
   * Early, Prompt and Late correlations
   */
  sbp_tracking_channel_correlation_dep_t corrs[3];
} sbp_msg_tracking_iq_dep_a_t;
/** Deprecated
 *
 * Deprecated.
 */

#define SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_MASK (0x3)
#define SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_SHIFT (0u)
#define SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_GET(flags) \
  (((flags) >> SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_SHIFT) & \
   SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_MASK)
#define SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_MASK)) \
                 << (SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_SHIFT))); \
  } while (0)

#define SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_DISABLED (0)
#define SBP_TRACKINGCHANNELSTATEDEPA_STATE_TRACKING_MODE_RUNNING (1)
typedef struct
{

  /**
   * Status of tracking channel
   */
  u8 state;
  /**
   * PRN-1 being tracked
   */
  u8 prn;
  /**
   * Carrier-to-noise density[dB Hz]
   */
  float cn0;
} sbp_tracking_channel_state_dep_a_t;
/** Deprecated
 *
 * Deprecated.
 */
#define SBP_MSG_TRACKING_STATE_DEP_A 0x0016

#define SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_MASK (0x3)
#define SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_SHIFT (0u)
#define SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_SHIFT) & \
   SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_MASK)
#define SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_MASK)) \
                 << (SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_DISABLED (0)
#define SBP_TRACKING_STATE_DEP_A_STATES_STATE_TRACKING_MODE_RUNNING (1)
typedef struct
{

  /**
   * Satellite tracking channel state
   */
  sbp_tracking_channel_state_dep_a_t states[42];
  /**
   * Number of items in states
   */
  u8 n_states;
} sbp_msg_tracking_state_dep_a_t;
/** Deprecated.
 *
 * Deprecated.
 */

#define SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_MASK (0x3)
#define SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_SHIFT (0u)
#define SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_GET(flags) \
  (((flags) >> SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_SHIFT) & \
   SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_MASK)
#define SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_MASK)) \
                 << (SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_SHIFT))); \
  } while (0)

#define SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_DISABLED (0)
#define SBP_TRACKINGCHANNELSTATEDEPB_STATE_TRACKING_MODE_RUNNING (1)

#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__MASK (0xff)
#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__SHIFT (0u)
#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__GET(flags) \
  (((flags) >> SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__SHIFT) & SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__MASK)
#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= \
     (((val) & (SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__MASK)) << (SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__SHIFT))); \
  } while (0)

#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__GPS_L1CA (0)
#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__GPS_L2CM (1)
#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__SBAS_L1CA (2)
#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__GLO_L1CA (3)
#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__GLO_L2CA (4)
#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__GPS_L1P (5)
#define SBP_TRACKINGCHANNELSTATEDEPB_SID_CODE__GPS_L2P (6)
typedef struct
{

  /**
   * Status of tracking channel
   */
  u8 state;
  /**
   * GNSS signal being tracked
   */
  sbp_gnss_signal_dep_t sid;
  /**
   * Carrier-to-noise density[dB Hz]
   */
  float cn0;
} sbp_tracking_channel_state_dep_b_t;
/** Deprecated.
 *
 * Deprecated.
 */
#define SBP_MSG_TRACKING_STATE_DEP_B 0x0013

#define SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_MASK (0x3)
#define SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_SHIFT (0u)
#define SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_SHIFT) & \
   SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_MASK)
#define SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_MASK)) \
                 << (SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_DISABLED (0)
#define SBP_TRACKING_STATE_DEP_B_STATES_STATE_TRACKING_MODE_RUNNING (1)

#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__MASK (0xff)
#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__SHIFT (0u)
#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__GET(flags) \
  (((flags) >> SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__SHIFT) & SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__MASK)
#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__SET(flags, val) \
  do \
  { \
    ((flags) |= (((val) & (SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__MASK)) \
                 << (SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__SHIFT))); \
  } while (0)

#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__GPS_L1CA (0)
#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__GPS_L2CM (1)
#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__SBAS_L1CA (2)
#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__GLO_L1CA (3)
#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__GLO_L2CA (4)
#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__GPS_L1P (5)
#define SBP_TRACKING_STATE_DEP_B_STATES_SID_CODE__GPS_L2P (6)
typedef struct
{

  /**
   * Signal tracking channel state
   */
  sbp_tracking_channel_state_dep_b_t states[28];
  /**
   * Number of items in states
   */
  u8 n_states;
} sbp_msg_tracking_state_dep_b_t;

#include <libsbp/unpacked/tracking_operators.h>
#include <libsbp/unpacked/tracking_packers.h>

#endif /* LIBSBP_TRACKING_MESSAGES_H */