/*
 * Copyright (C) 2015-2021 Swift Navigation Inc.
 * Contact: https://support.swiftnav.com
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

/*****************************************************************************
 * Automatically generated from yaml/swiftnav/sbp/ssr.yaml
 * with generate.py. Please do not hand edit!
 *****************************************************************************/

#ifndef LIBSBP_SSR_MACROS_H
#define LIBSBP_SSR_MACROS_H

#define SBP_MSG_SSR_ORBIT_CLOCK 0x05DD
#define SBP_MSG_SSR_CODE_BIASES 0x05E1
#define SBP_MSG_SSR_PHASE_BIASES 0x05E6
#define SBP_MSG_SSR_STEC_CORRECTION 0x05FB
#define SBP_MSG_SSR_GRIDDED_CORRECTION 0x05FC
#define SBP_MSG_SSR_TILE_DEFINITION 0x05F6
#define SBP_SATELLITEAPC_SATELLITE_TYPE_MASK (0x1f)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_SHIFT (0u)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GET(flags)      \
  (((flags) >> SBP_SATELLITEAPC_SATELLITE_TYPE_SHIFT) & \
   SBP_SATELLITEAPC_SATELLITE_TYPE_MASK)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_SET(flags, val)           \
  do {                                                            \
    ((flags) |= (((val) & (SBP_SATELLITEAPC_SATELLITE_TYPE_MASK)) \
                 << (SBP_SATELLITEAPC_SATELLITE_TYPE_SHIFT)));    \
  } while (0)

#define SBP_SATELLITEAPC_SATELLITE_TYPE_UNKNOWN_TYPE (0)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GPS_I (1)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GPS_II (2)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GPS_IIA (3)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GPS_IIR (4)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GPS_IIF (5)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GPS_III (6)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GLONASS (7)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GLONASS_M (8)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GLONASS_K1 (9)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_GALILEO (10)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_BEIDOU_2G (11)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_BEIDOU_2I (12)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_BEIDOU_2M (13)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_BEIDOU_3M_SECM (14)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_BEIDOU_3G_SECM (15)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_BEIDOU_3M_CAST (16)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_BEIDOU_3G_CAST (17)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_BEIDOU_3I_CAST (18)
#define SBP_SATELLITEAPC_SATELLITE_TYPE_QZSS (19)
#define SBP_MSG_SSR_SATELLITE_APC 0x0604
#define SBP_MSG_SSR_ORBIT_CLOCK_DEP_A 0x05DC
#define SBP_MSG_SSR_STEC_CORRECTION_DEP_A 0x05EB
#define SBP_MSG_SSR_GRIDDED_CORRECTION_NO_STD_DEP_A 0x05F0
#define SBP_MSG_SSR_GRIDDED_CORRECTION_DEP_A 0x05FA
#define SBP_MSG_SSR_GRID_DEFINITION_DEP_A 0x05F5

#endif /* LIBSBP_SSR_MACROS_H */
