name: Haskell
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - staging
    tags:
      - "*"
  pull_request:
    paths:
      - "haskell/**"
      - .github/workflows/haskell.yaml

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    outputs:
      artifact_name: ${{ steps.build.outputs.artifact_name }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-

      - uses: haskell/actions/setup@ce6c3a6f8cbe3bd6ce51b635b3f32ee792f22f91 # v2.4.7
        with:
          enable-stack: true

      - name: Build binaries
        id: build
        working-directory: ./haskell
        run: |
          VERSION="$(git describe --always --tags --dirty)"
          BUILD_TRIPLET="$(cc -dumpmachine)"
          ARTIFACT_NAME="sbp_tools_haskell-${VERSION}-${BUILD_TRIPLET}.zip"

          mkdir ./bins
          stack install --local-bin-path ./bins
          cd ./bins
          zip ../$ARTIFACT_NAME \
            sbp2json \
            sbp2prettyjson \
            sbp2yaml \
            json2sbp \
            json2json \
            sbp2nmea
          echo "artifact_name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ./haskell/${{ steps.build.outputs.artifact_name }}

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    name: Publish github release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: artifacts

      - name: Check artifact
        run: ls -l artifacts && test -s artifacts/${{ needs.build.outputs.artifact_name }}

      - name: Upload Release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "artifacts/*.zip"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
