name: Java
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - staging
    tags:
      - "*"
  pull_request:
    paths:
      - "java/**"
      - .github/workflows/java.yaml

permissions:
  contents: read

jobs:
  tests-java-1_8:
    name: Test
    runs-on: ubuntu-24.04
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Update apt and install unzip
        run: |
          apt-get update
          apt-get install -y unzip make
        shell: bash
      - uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
        with:
          gradle-version: 7.1.1
      - name: Run tests
        run: make test-java
