name: JavaScript
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - staging
    tags:
      - "*"
  pull_request:
    paths:
      - "javascript/**"
      - "spec/tests/**"
      - package.json
      - package-lock.json
      - .github/workflows/javascript.yaml

permissions:
  contents: read

jobs:
  coverage:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run tests
        shell: bash
        run: make test-javascript
