name: Python
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - staging
    tags:
      - "*"
  pull_request:
jobs:
  coverage:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: ./scripts/ci_prepare_python.bash

      - name: Run tests
        run: make test-python
        env:
          TOX_PARALLEL_NO_SPINNER: 1
