name: Python
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - staging
    tags:
      - "*"
  pull_request:
    paths:
      - "python/**"
      - "spec/tests/**"
      - requirements.txt
      - tox.ini
      - scripts/ci_prepare_python.bash
      - scripts/ci_test_python_legacy.bash
      - .github/workflows/python.yaml
jobs:
  coverage:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Install Python versions
        uses: actions/setup-python@v6
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
            3.13
            3.14

      - name: Setup
        run: ./scripts/ci_prepare_python.bash

      - name: Run tests
        run: make test-python
        env:
          TOX_PARALLEL_NO_SPINNER: 1

  legacy:
    name: Test (Python ${{ matrix.python }})
    runs-on: ubuntu-24.04
    container: python:${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        python: ["2.7", "3.7"]
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Run tests
        run: bash scripts/ci_test_python_legacy.bash
