on:
  push:
    branches:
      - master
      - staging
  pull_request:
    types: [opened, synchronize, reopened]
name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Sonarcloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=swift-nav
            -Dsonar.projectKey=swift-nav_libsbp_auto
            -Dsonar.sources=.
            -Dsonar.exclusions=java/**
            -Dsonar.verbose=true
            -Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=-

  C:
    name: C Code Coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5.3.1
      - name: Setup
        run: |
          sudo apt-get install llvm -y
      - name: Build and Run Tests
        env:
          CC: clang
          CXX: clang++
        run: |
          cmake -S c -B build -DCODE_COVERAGE=ON -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage &&
          build-wrapper-linux-x86-64 --out-dir ./bw-output cmake --build build -j4 --target ccov-all-export
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=swift-nav
            -Dsonar.projectName=libsbp-c
            -Dsonar.projectKey=swift-nav_libsbp_c
            -Dsonar.verbose=true
            -Dsonar.cfamily.threads=4
            -Dsonar.cfamily.llvm-cov.reportPath=./build/ccov/coverage.txt
            -Dsonar.sources=c/src/,c/include/
            -Dsonar.tests=c/test/
            -Dsonar.cfamily.build-wrapper-output=./bw-output
