on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AUTO }}
        with:
          args: >
            -Dsonar.organization=swift-nav
            -Dsonar.projectKey=swift-nav_libsbp_auto
            -Dsonar.sources=.
            -Dsonar.exclusions=java/**
            -Dsonar.verbose=true
            -Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=-
